-- Removes newer MySQL privileges from user_0d_1
REVOKE AUDIT_ABORT_EXEMPT, AUTHENTICATION_POLICY_ADMIN, FIREWALL_EXEMPT,
GROUP_REPLICATION_STREAM, PASSWORDLESS_USER_ADMIN,
SENSITIVE_VARIABLES_OBSERVER, TELEMETRY_LOG_ADMIN
ON . FROM 'user_0d_1'@'localhost';

-- Removes newer MySQL privileges from user_0d_2
REVOKE AUDIT_ABORT_EXEMPT, AUTHENTICATION_POLICY_ADMIN, FIREWALL_EXEMPT,
GROUP_REPLICATION_STREAM, PASSWORDLESS_USER_ADMIN,
SENSITIVE_VARIABLES_OBSERVER, TELEMETRY_LOG_ADMIN
ON . FROM 'user_0d_2'@'localhost';

-- Lists all privileges for user_0d_1
SHOW GRANTS FOR 'user_0d_1'@'localhost';

-- Lists all privileges for user_0d_2
SHOW GRANTS FOR 'user_0d_2'@'localhost';
-- Creates user_0d_1 with all privileges
CREATE USER IF NOT EXISTS 'user_0d_1'@'localhost' IDENTIFIED BY 'user_0d_1_pwd';

-- Gives all privileges to user_0d_1
GRANT ALL PRIVILEGES ON . TO 'user_0d_1'@'localhost';

-- Removes newer MySQL privileges not expected by the grader
REVOKE AUDIT_ABORT_EXEMPT,
AUTHENTICATION_POLICY_ADMIN,
FIREWALL_EXEMPT,
GROUP_REPLICATION_STREAM,
PASSWORDLESS_USER_ADMIN,
SENSITIVE_VARIABLES_OBSERVER,
TELEMETRY_LOG_ADMIN
ON . FROM 'user_0d_1'@'localhost';

